apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: open-market-app-api
  labels:
    app: open-market-app
    tier: backend
spec:
  replicas: 1
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  selector:
    matchLabels:
      app: open-market-app
      tier: backend
  open-market:
    metadata:
      name: open-market-app-api
      labels:
        app: open-market-app
        tier: backend
    spec:
      initContainers:
        - name: migrations
          image: localhost:5000/open-market_app:bdf3dca74d32a9c32d13607153cc8b0d14586a72
          command: ['python', 'manage.py', 'migrate']
          env:
          - name: WORKERS
            valueFrom:
              secretKeyRef:
                name: open-market-app-api
                key: workers
          - name: DATABASE_URL
            valueFrom:
              secretKeyRef:
                name: open-market-app-api
                key: database-url
          - name: SECRET_KEY
            valueFrom:
              secretKeyRef:
                name: open-market-app-api
                key: secret-key 
      containers:
      - image: localhost:5000/open-market_app:bdf3dca74d32a9c32d13607153cc8b0d14586a72
        name: open-market-app-api
        resources:
          requests:
            cpu: "20m"
            memory: "55M"
        livenessProbe:
          tcpSocket:
            port: 8000
          initialDelaySeconds: 90
          timeoutSeconds: 10
        readinessProbe:
          tcpSocket:
            port: 8000
          initialDelaySeconds: 30
          timeoutSeconds: 10
        env:
        - name: WORKERS
          valueFrom:
            secretKeyRef:
              name: open-market-app-api
              key: workers
        - name: DATABASE_URL
          valueFrom:
            secretKeyRef:
              name: open-market-app-api
              key: database-url
        - name: SECRET_KEY
          valueFrom:
            secretKeyRef:
              name: open-market-app-api
              key: secret-key
        ports:
        - containerPort: 8000
          name: http
        imagePullPolicy: IfNotPresent
      restartPolicy: Always