apiVersion: v1
data:
  POSTGRES_PASSWORD: cG9zdGdyZXMK
  POSTGRES_USER: cG9zdGdyZXMK
  POSTGRES_DB: b3Blbi1tYXJrZXQK
metadata:
  labels:
    app: template-app
    kubedb.com/kind: Postgres
    kubedb.com/name: template-app-postgres
  name: template-app-postgres-auth
type: Opaque
